const freshState=()=>({gold:12500,food:8000,essence:250,power:1250,level:1,seals:0,crystals:0,wins:0,buildings:{Keep:1,Farm:1,Barracks:1,Forge:1,"Dragon Sanctuary":1},troops:{Swordsmen:120,Archers:80,Guardians:30},dragons:{Drago:1,Nyx:0,Tharros:0,Kaelith:0,Veyra:0}});
let S=freshState();
try{const saved=localStorage.getItem("forgedDragonSave");if(saved)S=Object.assign(freshState(),JSON.parse(saved))}catch(e){}
function saveGame(){try{localStorage.setItem("forgedDragonSave",JSON.stringify(S))}catch(e){}}
const buildings={Keep:["🏰","Heart of Emberhold",1800,900],Farm:["🌾","Feeds the war host",900,300],Barracks:["⚔️","Raises warriors for clan war",1200,600],Forge:["🔥","Forges weapons against corrupted armies",1400,500],"Dragon Sanctuary":["🐉","Strengthens bonds with ancient dragons",2200,800]};
const troopData={Swordsmen:["🗡️",100,45,12],Archers:["🏹",130,55,15],Guardians:["🛡️",220,90,28]};
const dragonData={Drago:["🔥","First Flame • bonded",0,0],Nyx:["🌑","Shadow Wing • found beyond the Mist",180,1],Tharros:["⚡","Storm Dragon • waits beyond the Second Seal",260,2],Kaelith:["❄️","Frost Guardian • crystal-bound",340,4],Veyra:["✨","Crystal Seer • ancient bond",450,5]};
const realms=[
["Emberhold","🔥","Ash Raiders","Drago guards the road to the First Seal.",850,0,0],
["Mistwood","🌫️","Clan Nightfang","Nyx moves unseen beneath the black trees.",1450,1,1],
["Stormspire","⚡","Clan Iron Crown","Tharros answers from the mountain storm.",2200,2,2],
["Zephyr's Crossing","🪽","Xarath's Legion","Zephyr's path is revealed where the realms divide.",3000,3,3],
["Malaki's Reach","🗡️","Malaki's Shadow Guard","An old power waits behind the Fifth Seal.",3900,4,4],
["The Black Citadel","🏯","Xarath","The final crystal burns beneath the throne.",5200,6,6]
];
const clans=[["🔥","House Ember","Keepers of the First Flame"],["🌑","Nightfang","Hunters of the Mist Roads"],["⚔️","Iron Crown","Warriors of Stormspire"],["👹","Legion of Xarath","Corrupted armies of the Black Citadel"],["🗡️","Shadow Guard","Malaki's hidden war host"],["🐉","The Forged","A clan united by dragons, seals and mercy"]];
const $=s=>document.querySelector(s),fmt=n=>Math.floor(n).toLocaleString();
function card(ic,n,d,a,b,act,label,dis=false){return `<article class="card"><div class="icon">${ic}</div><h3>${n}</h3><p>${d}</p><div class="meta"><span>${a}</span><span>${b}</span></div>${act?`<button class="action" ${dis?"disabled":""} onclick="${act}">${label}</button>`:""}</article>`}
function sync(){saveGame();["gold","food","essence","power","level"].forEach(k=>$("#"+k).textContent=fmt(S[k]));$("#sealCount").textContent=`${S.seals} / 7`;$("#crystalCount").textContent=`${S.crystals} / 7`;document.querySelectorAll(".mirrorSeal").forEach(x=>x.textContent=`${S.seals} / 7`);document.querySelectorAll(".mirrorCrystal").forEach(x=>x.textContent=`${S.crystals} / 7`);$("#sealDots").innerHTML=dots(S.seals);$("#crystalDots").innerHTML=dots(S.crystals);render()}
function dots(n){return Array.from({length:7},(_,i)=>`<i class="relic ${i<n?"on":""}"></i>`).join("")}
function render(){let b="";for(const[n,d]of Object.entries(buildings)){let l=S.buildings[n],g=d[2]*l,f=d[3]*l;b+=card(d[0],n,d[1],`Level ${l}`,`🪙 ${fmt(g)} • 🌾 ${fmt(f)}`,`upgrade('${n}')`,"UPGRADE")}$("#buildings").innerHTML=b;
$("#troops").innerHTML=Object.entries(troopData).map(([n,d])=>card(d[0],n,`Attack ${d[3]} each`,`${fmt(S.troops[n])} troops`,`🪙 ${d[1]*10} • 🌾 ${d[2]*10}`,`train('${n}')`,"TRAIN 10")).join("");
$("#dragonList").innerHTML=Object.entries(dragonData).map(([n,d])=>{let l=S.dragons[n],locked=S.seals<d[3],cost=l?80*l:d[2];return card(d[0],n,d[1],l?`Level ${l}`:locked?`Needs ${d[3]} Seals`:"Sleeping",cost?`💎 ${cost}`:"Bonded",locked?"":`dragon('${n}')`,l?"TRAIN":"AWAKEN",locked)}).join("");
$("#realmMap").innerHTML=realms.map((r,i)=>{let locked=S.seals<r[5]||S.crystals<r[6];return `<article class="realm ${locked?"locked":""}"><div class="realm-icon">${r[1]}</div><h3>${r[0]}</h3><p class="story">${r[3]}</p><div class="meta"><span>⚔️ ${r[2]}</span><span>Power ${fmt(r[4])}</span></div><button class="action" ${locked?"disabled":""} onclick="realmFight(${i})">${locked?"SEALED":"MARCH TO BATTLE"}</button></article>`}).join("");
$("#clanList").innerHTML=clans.map((c,i)=>card(c[0],c[1],c[2],i<3?"Rival Clan":i<5?"Enemy Faction":"Player Clan",i<5?"Territory War":"Form / Join","","")).join("");
let q=[["The First Seal",S.seals>=1,"Defeat the Ash Raiders"],["Bond with Nyx",S.dragons.Nyx>0,"Find Nyx beyond the Mist"],["Awaken Tharros",S.dragons.Tharros>0,"Break the Second Seal"],["Find Zephyr's Path",S.seals>=3&&S.crystals>=3,"Reach Zephyr's Crossing"],["Face Malaki's Guard",S.seals>=4,"Open the road to Malaki's Reach"],["Seven Crystals",S.crystals>=7,"Recover all Seven Crystals"]];$("#questList").innerHTML=q.map(x=>card(x[1]?"✅":"📜",x[0],x[2],x[1]?"Complete":"In progress",x[1]?"FORGED":"LOCKED","","")).join("")}
function armyPower(){return Object.entries(S.troops).reduce((a,[n,c])=>a+c*troopData[n][3],0)+Object.values(S.dragons).reduce((a,l)=>a+l*350,0)+S.buildings.Forge*100}
function realmFight(i){battleSetup(i)}
function upgrade(n){let l=S.buildings[n],d=buildings[n],g=d[2]*l,f=d[3]*l;if(S.gold<g||S.food<f)return msg("Not enough resources.");S.gold-=g;S.food-=f;S.buildings[n]++;S.power+=250*l;if(n==="Keep")S.level++;msg(`${n} rises to Level ${l+1}.`);sync()}
function train(n){let d=troopData[n],g=d[1]*10,f=d[2]*10;if(S.gold<g||S.food<f)return msg("The stores cannot support those troops.");S.gold-=g;S.food-=f;S.troops[n]+=10;S.power+=d[3]*10;msg(`10 ${n} join the Forged war host.`);sync()}
function dragon(n){let d=dragonData[n],l=S.dragons[n],cost=l?80*l:d[2];if(S.seals<d[3])return msg(`${n} cannot be reached until more Seals are broken.`);if(S.essence<cost)return msg("Not enough Dragon Essence.");S.essence-=cost;S.dragons[n]=l+1;S.power+=500*(l+1);msg(`🐉 ${n} answers the call. The bond grows stronger.`);sync()}
function msg(t){$("#battleLog").textContent=t}
document.querySelectorAll(".tabs button").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".tabs button,.tab").forEach(x=>x.classList.remove("active"));btn.classList.add("active");$("#"+btn.dataset.tab).classList.add("active")}));
sync();


// BABYLON.JS — 3D EMBERHOLD
(function initEmberhold3D(){
 const canvas=document.getElementById("realmCanvas"); if(!canvas||!window.BABYLON)return;
 const engine=new BABYLON.Engine(canvas,true,{preserveDrawingBuffer:true,stencil:true});
 const scene=new BABYLON.Scene(engine); scene.clearColor=new BABYLON.Color4(.035,.018,.01,1);
 scene.fogMode=BABYLON.Scene.FOGMODE_EXP2; scene.fogDensity=.018; scene.fogColor=new BABYLON.Color3(.09,.045,.02);
 const camera=new BABYLON.ArcRotateCamera("ForgedCamera",-Math.PI/2,1.05,34,new BABYLON.Vector3(0,2,0),scene);
 camera.attachControl(canvas,true); camera.lowerRadiusLimit=16; camera.upperRadiusLimit=48; camera.lowerBetaLimit=.55; camera.upperBetaLimit=1.35; camera.wheelDeltaPercentage=.01; camera.pinchDeltaPercentage=.01;
 const hemi=new BABYLON.HemisphericLight("moon",new BABYLON.Vector3(0,1,0),scene); hemi.intensity=.48; hemi.diffuse=new BABYLON.Color3(.75,.5,.3);
 const fire=new BABYLON.PointLight("ember",new BABYLON.Vector3(0,8,2),scene); fire.diffuse=new BABYLON.Color3(1,.28,.04); fire.intensity=2.2; fire.range=28;
 function mat(name,color,emissive){const m=new BABYLON.StandardMaterial(name,scene);m.diffuseColor=BABYLON.Color3.FromHexString(color);m.specularColor=new BABYLON.Color3(.08,.06,.04);if(emissive)m.emissiveColor=BABYLON.Color3.FromHexString(emissive);return m}
 const basalt=mat("Forged basalt","#3b2920"),stone=mat("ember stone","#6a4933"),bronze=mat("ancient bronze","#7a451d"),lava=mat("forged fire","#7a1905","#ff3b05"),crystal=mat("crystal","#164a5a","#19d3ff");
 const ground=BABYLON.MeshBuilder.CreateCylinder("Emberhold",{height:1.8,diameterTop:29,diameterBottom:24,tessellation:8},scene);ground.position.y=-1;ground.material=basalt;
 const ring=BABYLON.MeshBuilder.CreateTorus("Seal Ring",{diameter:20,thickness:.45,tessellation:32},scene);ring.rotation.x=Math.PI/2;ring.position.y=.05;ring.material=bronze;
 function box(n,x,y,z,w,h,d,material=stone){const b=BABYLON.MeshBuilder.CreateBox(n,{width:w,height:h,depth:d},scene);b.position.set(x,y,z);b.material=material;b.metadata={building:n};return b}
 function tower(n,x,z,h=5){const t=BABYLON.MeshBuilder.CreateCylinder(n,{height,diameter:3.1,tessellation:6},scene);t.position.set(x,h/2,z);t.material=stone;t.metadata={building:n};const crown=BABYLON.MeshBuilder.CreateCylinder(n+" crown",{height:.9,diameterTop:3.8,diameterBottom:3.2,tessellation:6},scene);crown.position.set(x,h+.2,z);crown.material=bronze;crown.metadata=t.metadata;return t}
 box("Keep",0,2.6,0,7,5.2,6);box("Keep",-0,5.8,0,4.6,1.3,4.1,bronze);
 tower("Keep",-4,-3,5.5);tower("Keep",4,-3,5.5);tower("Keep",-4,3,5.5);tower("Keep",4,3,5.5);
 box("Barracks",-8,1.35,3,5,2.7,4);box("Forge",8,1.35,3,5,2.7,4);box("Dragon Sanctuary",7,1.2,-5,5.5,2.4,4.5);box("Farm",-7,.7,-5,5,1.4,4);
 for(let i=0;i<7;i++){const a=i/7*Math.PI*2;const c=BABYLON.MeshBuilder.CreatePolyhedron("Crystal "+(i+1),{type:1,size:.65},scene);c.position.set(Math.cos(a)*11,1,Math.sin(a)*11);c.material=i<S.crystals?crystal:basalt}
 for(let i=0;i<12;i++){const a=i/12*Math.PI*2;const p=BABYLON.MeshBuilder.CreateCylinder("wall",{height:2.5,diameter:2.3,tessellation:6},scene);p.position.set(Math.cos(a)*12,1.25,Math.sin(a)*12);p.material=stone}
 scene.onPointerObservable.add(pi=>{if(pi.type!==BABYLON.PointerEventTypes.POINTERPICK)return;const pick=pi.pickInfo;if(!pick?.hit)return;let m=pick.pickedMesh;const n=m?.metadata?.building;if(n&&buildings[n]){document.getElementById("buildingInfo").textContent=n.toUpperCase()+" — "+buildings[n][1].toUpperCase()+" • LEVEL "+S.buildings[n];}});
 engine.runRenderLoop(()=>{fire.intensity=1.8+Math.sin(performance.now()/180)*.35;scene.render()});window.addEventListener("resize",()=>engine.resize());
})();


// Separate battlefield: formations are rendered as lightweight units rather than hundreds of expensive models.
let battle=null,frame=0;const bf=$('#battlefield'),bc=$('#battleCanvas'),bx=bc.getContext('2d');
function battleSetup(realmIndex){const r=realms[realmIndex],total=Math.min(300,Math.max(40,Object.values(S.troops).reduce((a,n)=>a+n,0)));const enemy=Math.min(300,Math.max(30,Math.round(r[4]/18)));battle={realmIndex,realm:r,phase:'march',friendly:total,enemy,baseFriendly:total,baseEnemy:enemy,started:false,ended:false,t:0,arrows:[],smoke:[]};$('#battleTitle').textContent='BATTLE FOR '+r[0].toUpperCase();$('#battlePhase').textContent='MARCHING FROM EMBERHOLD';$('#friendlyCount').textContent=total+' forged troops';$('#enemyCount').textContent=enemy+' '+r[2].toLowerCase();$('#battleNarration').textContent='Infantry form ranks. Archers take the ridge. Drago circles above.';$('#beginClash').hidden=false;$('#returnKingdom').hidden=true;bf.hidden=false;requestAnimationFrame(battleLoop)}
function formation(count,side){const cols=Math.ceil(Math.sqrt(count*1.6)),out=[];for(let i=0;i<count;i++){const row=Math.floor(i/cols),col=i%cols;out.push({x:side==='f'?160+col*13:bc.width-160-col*13,y:430-row*12,kind:row%4===0?'archer':'infantry'})}return out}
function battleLoop(t){if(!battle||bf.hidden)return;const dt=Math.min(.035,(t-frame||16)/1000);frame=t;drawBattle(dt);requestAnimationFrame(battleLoop)}
function drawBattle(dt){const b=battle,g=bx,W=bc.width,H=bc.height;const sky=g.createLinearGradient(0,0,0,H);sky.addColorStop(0,'#243d64');sky.addColorStop(.55,'#d67b45');sky.addColorStop(1,'#30251b');g.fillStyle=sky;g.fillRect(0,0,W,H);g.fillStyle='rgba(255,225,167,.8)';g.beginPath();g.arc(W*.62,110,58,0,Math.PI*2);g.fill();for(let i=0;i<8;i++){const x=i*200;g.fillStyle=i%2?'#263a39':'#1c3034';g.beginPath();g.moveTo(x,H*.69);g.lineTo(x+110,H*.28+(i%3)*40);g.lineTo(x+230,H*.69);g.fill()}g.fillStyle='#3d2f22';g.fillRect(0,H*.68,W,H*.32);g.fillStyle='#6d5530';for(let i=0;i<W;i+=32)g.fillRect(i,H*.7,2,H*.3);
 const step=b.phase==='march'?Math.min(b.t*.12,1):b.phase==='clash'?.55:1;const friends=formation(b.friendly,'f'),foes=formation(b.enemy,'e');b.t+=dt;function unit(u,friend){const tx=friend?u.x+(W*.34*step):u.x-(W*.34*step);g.save();g.translate(tx,u.y);g.fillStyle=friend?'#31516b':'#6b2b2b';g.fillRect(-4,-9,8,16);g.fillStyle=friend?'#e4b66a':'#d99873';g.beginPath();g.arc(0,-14,5,0,Math.PI*2);g.fill();g.fillStyle=friend?'#c93d2d':'#382126';g.fillRect(-7,7,14,3);if(u.kind==='archer'){g.strokeStyle='#d5a85d';g.beginPath();g.moveTo(-7,-6);g.lineTo(8,-3);g.stroke()}g.restore()}friends.forEach(u=>unit(u,true));foes.forEach(u=>unit(u,false));
 // banners and Drago's pass
 g.fillStyle='#bd3b2d';g.fillRect(125,H*.46,5,105);g.fillRect(130,H*.46,52,24);g.fillStyle='#1f2027';g.fillRect(W-130,H*.46,5,105);g.fillRect(W-180,H*.46,52,24);const dx=W*.54+Math.sin(b.t*.65)*W*.3,dy=130+Math.sin(b.t*1.7)*24;g.save();g.translate(dx,dy);g.fillStyle='#351b1b';g.beginPath();g.ellipse(0,0,35,12,0,0,Math.PI*2);g.fill();g.fillStyle='#c64d31';g.beginPath();g.moveTo(-8,0);g.lineTo(-70,-32);g.lineTo(-32,20);g.fill();g.beginPath();g.moveTo(10,0);g.lineTo(70,-32);g.lineTo(34,20);g.fill();g.restore();
 if(b.phase==='clash'){for(let i=0;i<5;i++){const ax=W*.47+(i*19);g.strokeStyle='#e9d5a4';g.lineWidth=2;g.beginPath();g.moveTo(230+i*18,350);g.lineTo(ax,260+i*10);g.stroke()}for(let i=0;i<10;i++){g.fillStyle='rgba(40,40,40,.3)';g.beginPath();g.arc(W*.5+(i%5)*17,395+Math.floor(i/5)*15,14+b.t%4,0,Math.PI*2);g.fill()}}
 if(b.phase==='victory'||b.phase==='defeat'){g.fillStyle='rgba(5,7,9,.5)';g.fillRect(0,0,W,H);g.fillStyle=b.phase==='victory'?'#f3c66f':'#e77c62';g.font='bold 42px Georgia';g.textAlign='center';g.fillText(b.phase==='victory'?'VICTORY FOR THE FORGED':'THE ARMY RETREATS',W/2,H*.45)} }
function beginClash(){if(!battle||battle.started)return;battle.started=true;battle.phase='clash';$('#beginClash').hidden=true;$('#battlePhase').textContent='FORMATIONS CLASH';$('#battleNarration').textContent='Arrows rise. Shields lock. Drago dives through the enemy line.';setTimeout(resolveBattle,4300)}
function resolveBattle(){const b=battle;const strength=armyPower()*(.82+Math.random()*.38),won=strength>=b.realm[4];const casualties=Math.max(2,Math.round(b.baseFriendly*(won?.07:.18)));Object.keys(S.troops).forEach(n=>S.troops[n]=Math.max(0,S.troops[n]-Math.ceil(casualties/3)));S.food=Math.max(0,S.food-Math.ceil(b.baseFriendly*.45));b.phase=won?'victory':'defeat';b.ended=true;if(won){S.wins++;S.gold+=900+b.realmIndex*500;S.food+=450+b.realmIndex*250;S.essence+=35+b.realmIndex*10;S.power+=150+b.realmIndex*90;S.crystals=Math.min(7,S.crystals+1);if(b.realmIndex<5)S.seals=Math.min(7,Math.max(S.seals,b.realmIndex+1));$('#battleNarration').textContent='Territory captured. '+casualties+' troops fell. Loot and relics return to Emberhold.'}else{S.power=Math.max(0,S.power-60);$('#battleNarration').textContent='The army retreats. '+casualties+' troops were lost and food stores were spent. Rebuild before marching again.'}$('#battlePhase').textContent=won?'TERRITORY CAPTURED':'RETREAT TO EMBERHOLD';$('#friendlyCount').textContent='Casualties: '+casualties;$('#returnKingdom').hidden=false;sync()}
function returnKingdom(){bf.hidden=true;battle=null;document.querySelector('[data-tab="kingdom"]').click();msg('Battle resolved. Emberhold reflects casualties, food use, loot, and captured territory.')}
$('#beginClash').onclick=beginClash;$('#returnKingdom').onclick=returnKingdom;$('#retreatBattle').onclick=returnKingdom;
